# Generated by Django 2.1.3 on 2018-11-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawBitcoinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField()),
                ('price_coinbase', models.FloatField()),
                ('price_bitstamp', models.FloatField()),
                ('volume_btc_coinbase', models.FloatField()),
                ('volume_btc_bitstamp', models.FloatField()),
                ('volume_currency_coinbase', models.FloatField()),
                ('volume_currency_bitstamp', models.FloatField()),
                ('wighted_price_coinbase', models.FloatField()),
                ('wighted_price_bitstamp', models.FloatField()),
            ],
        ),
    ]
