# Generated by Django 2.1.3 on 2018-11-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawBitcoinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(unique=True)),
                ('price_coinbase', models.FloatField(null=True)),
                ('price_bitstamp', models.FloatField(null=True)),
                ('volume_btc_coinbase', models.FloatField(null=True)),
                ('volume_btc_bitstamp', models.FloatField(null=True)),
                ('volume_currency_coinbase', models.FloatField(null=True)),
                ('volume_currency_bitstamp', models.FloatField(null=True)),
                ('wighted_price_coinbase', models.FloatField(null=True)),
                ('wighted_price_bitstamp', models.FloatField(null=True)),
            ],
        ),
    ]
