# Generated by Django 2.1.3 on 2018-11-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawbitcoindata',
            name='datetime',
            field=models.DateField(unique=True),
        ),
    ]
