# Generated by Django 2.1.3 on 2018-11-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetapp', '0002_auto_20181129_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawbitcoindata',
            name='price_bitstamp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawbitcoindata',
            name='price_coinbase',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawbitcoindata',
            name='volume_btc_bitstamp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawbitcoindata',
            name='volume_btc_coinbase',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawbitcoindata',
            name='volume_currency_bitstamp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawbitcoindata',
            name='volume_currency_coinbase',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawbitcoindata',
            name='wighted_price_bitstamp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rawbitcoindata',
            name='wighted_price_coinbase',
            field=models.FloatField(null=True),
        ),
    ]
