# Generated by Django 2.1.3 on 2018-11-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophetapp', '0003_auto_20181129_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawbitcoindata',
            name='id',
        ),
        migrations.AlterField(
            model_name='rawbitcoindata',
            name='datetime',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
